Add a test for a close pair internal check failure.
Running this test causes a failure such as
InternalException: Internal check failure: Pair "8" and "10" not found
in close pairs list at distance -5.34047

when running with internal checks turned on.
Relates salilab/imp#853.